/* K-MUSIC V3 — bibliothèque locale + profondeur dynamique */
const audio=document.getElementById('audio'),musicInput=document.getElementById('musicInput'),addMusic=document.getElementById('addMusic'),addFirstMusic=document.getElementById('addFirstMusic'),library=document.getElementById('library'),search=document.getElementById('search'),songCount=document.getElementById('songCount'),heroCount=document.getElementById('heroCount');
const miniPlayer=document.getElementById('miniPlayer'),miniCover=document.getElementById('miniCover'),miniTitle=document.getElementById('miniTitle'),miniArtist=document.getElementById('miniArtist'),miniPlay=document.getElementById('miniPlay'),miniPrevious=document.getElementById('miniPrevious'),miniNext=document.getElementById('miniNext'),miniProgress=document.getElementById('miniProgress'),miniEq=document.getElementById('miniEq'),openPlayer=document.getElementById('openPlayer');
const playerScreen=document.getElementById('playerScreen'),playerBackdrop=document.getElementById('playerBackdrop'),closePlayer=document.getElementById('closePlayer'),coverStage=document.getElementById('coverStage'),bigCover=document.getElementById('bigCover'),bigTitle=document.getElementById('bigTitle'),bigArtist=document.getElementById('bigArtist'),bigAlbum=document.getElementById('bigAlbum'),playerFavorite=document.getElementById('playerFavorite'),play=document.getElementById('play'),previous=document.getElementById('previous'),next=document.getElementById('next'),shuffle=document.getElementById('shuffle'),repeat=document.getElementById('repeat'),progress=document.getElementById('progress'),currentTime=document.getElementById('currentTime'),duration=document.getElementById('duration');
let songs=[],currentSong=-1,shuffleEnabled=false,repeatEnabled=false,currentFilter='all',database=null,activeObjectUrl=null;

function openDatabase(){return new Promise((resolve,reject)=>{const request=indexedDB.open('KMusicDatabase',1);request.onupgradeneeded=e=>{const db=e.target.result;if(!db.objectStoreNames.contains('songs'))db.createObjectStore('songs',{keyPath:'id'})};request.onsuccess=e=>{database=e.target.result;resolve(database)};request.onerror=()=>reject(request.error)})}
function saveSong(song){return new Promise((resolve,reject)=>{const tx=database.transaction(['songs'],'readwrite');tx.objectStore('songs').put(song);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
function loadSongs(){return new Promise((resolve,reject)=>{const tx=database.transaction(['songs'],'readonly'),req=tx.objectStore('songs').getAll();req.onsuccess=()=>{songs=req.result||[];resolve()};req.onerror=()=>reject(req.error)})}
async function init(){try{await openDatabase();await loadSongs();renderLibrary()}catch(e){console.error("Impossible d'ouvrir la bibliothèque",e)}}init();

function openFilePicker(){musicInput.click()}addMusic.addEventListener('click',openFilePicker);addFirstMusic.addEventListener('click',openFilePicker);
musicInput.addEventListener('change',async e=>{for(const file of Array.from(e.target.files)){if(!file.type.startsWith('audio/')&&!isAudioExtension(file.name))continue;const song={id:crypto.randomUUID(),name:file.name,title:removeExtension(file.name),artist:'Artiste inconnu',album:'Album inconnu',year:'',artwork:null,favorite:false,file};try{const m=await readMetadata(file);if(m){song.title=m.title||song.title;song.artist=m.artist||song.artist;song.album=m.album||song.album;song.year=m.year||'';song.artwork=m.artwork||null}}catch(err){console.log('Métadonnées non disponibles',err)}await saveSong(song);songs.push(song)}musicInput.value='';renderLibrary()});
function readMetadata(file){return new Promise(resolve=>{if(typeof jsmediatags==='undefined'){resolve(null);return}jsmediatags.read(file,{onSuccess:tag=>{const t=tag.tags||{};let artwork=null;if(t.picture){const bytes=new Uint8Array(t.picture.data);let binary='';for(let i=0;i<bytes.length;i++)binary+=String.fromCharCode(bytes[i]);artwork=`data:${t.picture.format};base64,${btoa(binary)}`}resolve({title:t.title||'',artist:t.artist||'',album:t.album||'',year:t.year||'',artwork})},onError:()=>resolve(null)})})}

function renderLibrary(){const q=search.value.trim().toLowerCase();const visible=songs.filter(s=>`${s.title} ${s.artist} ${s.album}`.toLowerCase().includes(q)&&(currentFilter==='all'||(currentFilter==='favorites'&&s.favorite)));songCount.textContent=`${songs.length} ${songs.length>1?'morceaux':'morceau'}`;heroCount.textContent=`${songs.length} ${songs.length>1?'titres':'titre'}`;library.innerHTML='';if(!visible.length){library.innerHTML=`<div class="empty glass-panel"><div class="empty-cover"><div class="empty-disc">♪</div></div><h3>${songs.length?'Aucun résultat':'Ta bibliothèque est vide'}</h3><p>${songs.length?'Essaie un autre titre, artiste ou album.':'Ajoute quelques morceaux et K-Music prend vie.'}</p>${songs.length?'':'<button class="primary-button pressable" id="emptyAdd">Ajouter de la musique</button>'}</div>`;document.getElementById('emptyAdd')?.addEventListener('click',openFilePicker);return}visible.forEach((song,i)=>{const index=songs.findIndex(x=>x.id===song.id),el=document.createElement('article');el.className=`song ${index===currentSong?'is-current':''}`;el.style.animationDelay=`${Math.min(i*28,220)}ms`;el.innerHTML=`<div class="song-cover">${song.artwork?`<img src="${song.artwork}" alt="">`:'♪'}</div><div class="song-info"><div class="song-title">${escapeHTML(song.title)}</div><div class="song-artist">${escapeHTML(song.artist)}</div></div><button class="song-heart pressable ${song.favorite?'favorite':''}" aria-label="Favori">${song.favorite?'♥':'♡'}</button>`;el.addEventListener('click',ev=>{if(!ev.target.closest('.song-heart'))playSong(index)});el.querySelector('.song-heart').addEventListener('click',ev=>{ev.stopPropagation();toggleFavorite(index)});library.appendChild(el)})}
async function toggleFavorite(index){if(!songs[index])return;songs[index].favorite=!songs[index].favorite;await saveSong(songs[index]);updateFavoriteUI();renderLibrary()}
function updateFavoriteUI(){if(currentSong<0||!songs[currentSong])return;const fav=songs[currentSong].favorite;playerFavorite.textContent=fav?'♥':'♡';playerFavorite.classList.toggle('favorite',fav)}

function playSong(index){if(!songs[index])return;currentSong=index;const song=songs[index];if(activeObjectUrl)URL.revokeObjectURL(activeObjectUrl);activeObjectUrl=URL.createObjectURL(song.file);audio.src=activeObjectUrl;updatePlayer(song);renderLibrary();audio.play().then(updatePlayButtons).catch(e=>console.error('Lecture impossible',e))}
function updatePlayer(song){miniTitle.textContent=song.title;miniArtist.textContent=song.artist;bigTitle.textContent=song.title;bigArtist.textContent=song.artist;bigAlbum.textContent=song.album&&song.album!=='Album inconnu'?[song.album,song.year].filter(Boolean).join(' • '):'';if(song.artwork){miniCover.innerHTML=`<img src="${song.artwork}" alt="">`;bigCover.innerHTML=`<img src="${song.artwork}" alt="">`;playerBackdrop.style.setProperty('--player-art',`url("${song.artwork}")`);playerBackdrop.classList.add('has-art');updateDynamicColor(song.artwork)}else{miniCover.innerHTML='♪';bigCover.innerHTML='<div class="cover-placeholder"><span>K</span></div>';playerBackdrop.classList.remove('has-art');setDynamicRGB(130,78,255)}miniPlayer.classList.remove('hidden');updateFavoriteUI();updateMediaSession()}
function togglePlay(){if(currentSong===-1)return;audio.paused?audio.play().catch(console.error):audio.pause()}play.addEventListener('click',togglePlay);miniPlay.addEventListener('click',togglePlay);audio.addEventListener('play',updatePlayButtons);audio.addEventListener('pause',updatePlayButtons);
function updatePlayButtons(){const playing=!audio.paused;play.innerHTML=`<span>${playing?'Ⅱ':'▶'}</span>`;miniPlay.innerHTML=`<span>${playing?'Ⅱ':'▶'}</span>`;miniEq.classList.toggle('paused',!playing);if('mediaSession'in navigator)navigator.mediaSession.playbackState=playing?'playing':'paused'}
function nextSong(){if(!songs.length)return;let n;if(shuffleEnabled){if(songs.length===1)n=currentSong;else do{n=Math.floor(Math.random()*songs.length)}while(n===currentSong)}else{n=currentSong+1;if(n>=songs.length)n=0}playSong(n)}
function previousSong(){if(!songs.length)return;if(audio.currentTime>3){audio.currentTime=0;return}let p=currentSong-1;if(p<0)p=songs.length-1;playSong(p)}next.addEventListener('click',nextSong);miniNext.addEventListener('click',nextSong);previous.addEventListener('click',previousSong);miniPrevious.addEventListener('click',previousSong);audio.addEventListener('ended',()=>{if(repeatEnabled){audio.currentTime=0;audio.play();return}nextSong()});
shuffle.addEventListener('click',()=>{shuffleEnabled=!shuffleEnabled;shuffle.classList.toggle('active',shuffleEnabled)});repeat.addEventListener('click',()=>{repeatEnabled=!repeatEnabled;repeat.classList.toggle('active',repeatEnabled)});

audio.addEventListener('loadedmetadata',()=>duration.textContent=formatTime(audio.duration));audio.addEventListener('timeupdate',()=>{if(!audio.duration)return;const pct=audio.currentTime/audio.duration*100;progress.value=pct;progress.style.setProperty('--progress-fill',`${pct}%`);miniProgress.style.width=`${pct}%`;currentTime.textContent=formatTime(audio.currentTime)});progress.addEventListener('input',()=>{if(!audio.duration)return;audio.currentTime=progress.value/100*audio.duration;progress.style.setProperty('--progress-fill',`${progress.value}%`)});
search.addEventListener('input',renderLibrary);document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');currentFilter=btn.dataset.filter;renderLibrary()}));

function openFullPlayer(){if(currentSong===-1)return;playerScreen.classList.add('open');playerScreen.setAttribute('aria-hidden','false');document.body.classList.add('player-open')}function closeFullPlayer(){playerScreen.classList.remove('open');playerScreen.setAttribute('aria-hidden','true');document.body.classList.remove('player-open');resetCoverTilt()}openPlayer.addEventListener('click',openFullPlayer);closePlayer.addEventListener('click',closeFullPlayer);playerFavorite.addEventListener('click',()=>{if(currentSong!==-1)toggleFavorite(currentSong)});
let touchStartY=null,touchLastY=null;playerScreen.addEventListener('touchstart',e=>{touchStartY=e.touches[0]?.clientY??null;touchLastY=touchStartY},{passive:true});playerScreen.addEventListener('touchmove',e=>{touchLastY=e.touches[0]?.clientY??touchLastY},{passive:true});playerScreen.addEventListener('touchend',()=>{if(touchStartY!==null&&touchLastY!==null&&touchLastY-touchStartY>105)closeFullPlayer();touchStartY=touchLastY=null});
coverStage.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const r=coverStage.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;bigCover.style.setProperty('--tilt-x',`${(0.5-y)*8}deg`);bigCover.style.setProperty('--tilt-y',`${(x-0.5)*8}deg`)});coverStage.addEventListener('pointerleave',resetCoverTilt);function resetCoverTilt(){bigCover.style.setProperty('--tilt-x','0deg');bigCover.style.setProperty('--tilt-y','0deg')}

function updateDynamicColor(src){const img=new Image();img.onload=()=>{try{const c=document.createElement('canvas'),ctx=c.getContext('2d',{willReadFrequently:true});c.width=c.height=32;ctx.drawImage(img,0,0,32,32);const d=ctx.getImageData(0,0,32,32).data;let r=0,g=0,b=0,w=0;for(let i=0;i<d.length;i+=16){const rr=d[i],gg=d[i+1],bb=d[i+2],br=(rr+gg+bb)/3;if(br<28||br>235)continue;const sat=Math.max(rr,gg,bb)-Math.min(rr,gg,bb),ww=1+sat/120;r+=rr*ww;g+=gg*ww;b+=bb*ww;w+=ww}if(!w)return setDynamicRGB(130,78,255);r=Math.round(r/w);g=Math.round(g/w);b=Math.round(b/w);const max=Math.max(r,g,b);if(max<125){const f=125/Math.max(max,1);r=Math.min(255,Math.round(r*f));g=Math.min(255,Math.round(g*f));b=Math.min(255,Math.round(b*f))}setDynamicRGB(r,g,b)}catch{setDynamicRGB(130,78,255)}};img.onerror=()=>setDynamicRGB(130,78,255);img.src=src}function setDynamicRGB(r,g,b){document.documentElement.style.setProperty('--dynamic-rgb',`${r},${g},${b}`)}

function updateMediaSession(){if(!('mediaSession'in navigator)||currentSong===-1)return;const s=songs[currentSong],art=s.artwork?[{src:s.artwork,sizes:'512x512',type:s.artwork.startsWith('data:image/png')?'image/png':'image/jpeg'}]:[];navigator.mediaSession.metadata=new MediaMetadata({title:s.title,artist:s.artist,album:s.album,artwork:art});safeMediaAction('play',()=>audio.play());safeMediaAction('pause',()=>audio.pause());safeMediaAction('previoustrack',previousSong);safeMediaAction('nexttrack',nextSong);safeMediaAction('seekbackward',d=>audio.currentTime=Math.max(0,audio.currentTime-(d.seekOffset||10)));safeMediaAction('seekforward',d=>audio.currentTime=Math.min(audio.duration||Infinity,audio.currentTime+(d.seekOffset||10)))}function safeMediaAction(a,h){try{navigator.mediaSession.setActionHandler(a,h)}catch{}}
function formatTime(s){if(!Number.isFinite(s)||s<0)return'0:00';return`${Math.floor(s/60)}:${Math.floor(s%60).toString().padStart(2,'0')}`}function removeExtension(f){return f.replace(/\.[^/.]+$/,'')}function isAudioExtension(f){return /\.(mp3|m4a|aac|wav|flac|alac)$/i.test(f)}function escapeHTML(t){return String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}window.addEventListener('beforeunload',()=>{if(activeObjectUrl)URL.revokeObjectURL(activeObjectUrl)});
